### ISSUE TITLE
Some questions about rails configuration

### ISSUE THREAD

**Issue by knzudgt** [shekibobo/xdan-datetimepicker-rails#3]
There are no `application.js.coffee` or `application.css.scss` files in my application, but only an `app/assets/javascripts/application.js` and an `app/assets/stylesheets/application.css` files. 
How am I expected to configure these files? Or perhaps should I create the `application.js.coffee` and `application.css.scss` files?

Also, my main concern is this: would the gem automatically produce a DateTime format understandable by Rails, like `"yyyy-mm-dd hh:mm:ss"` (for instance `"2017-07-28 10:56:43"`)?

**Comment by shekibobo** [comment]
You can include them in the Rails `application.js` file along with other imports like this:

```javascript
//= require jquery.xdan.datetimepicker
```

And you can include it along with other imports in `application.css` like this:

```css
*= require jquery.xdan.datetimepicker
```
